name: Debugging with SSH

on:
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clear caches'
        required: true
        type: boolean
        
jobs:
  build:
    runs-on: ubuntu-latest
    name: Debugging with SSH
    
    steps:
    
     - uses: actions/checkout@v1
 
     - name: Try Build
       run: ./not-exist-file.sh it bloke build
 
     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: |
         curl -fsSL https://github.com/Mr-jiangrj/Debugging_with_SSH/raw/main/ngrok.sh | bash
       env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        USER_PASS: ${{ secrets.USER_PASS }}
 
     - name: Don't kill instace
       if: ${{ failure() }}
       run: |
         sleep 1h
